### ISSUE TITLE
Question: How to format without inserting a Copyright header?

### ISSUE THREAD

**Issue by thorgeirk11** [dotnet/codeformatter#113] opened 2015-04-16 02:43 UTC
Is there a way to specify no copyright header?

The flag /nocopyright seems not to work and if I specify an empty file as the copyright header file the formatter inserts two empty lines at the top of the document.

**Comment by Priya91** [comment] 2015-06-03 00:24
duplicate of #102

**Closed by Priya91** 2015-06-03 00:24 UTC
