### ISSUE TITLE
Codeformatter does met own style formatting rules.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/codeformatter#52] opened 2015-02-09 20:20 UTC
Codeformatter does met it's own style formatting rules.

Kind of ironic!
```
   public ImmutableArray<string> CopyrightHeader
        {
            get { return _options.CopyrightHeader; }
            set { _options.CopyrightHeader = value; }
        }

        public ImmutableArray<string[]> PreprocessorConfigurations
        {
            get { return _options.PreprocessorConfigurations; }
            set { _options.PreprocessorConfigurations = value; }
        }

        public ImmutableArray<string> FileNames
        {
            get { return _options.FileNames; }
            set { _options.FileNames = value; }
        }

        public IFormatLogger FormatLogger
        {
            get { return _options.FormatLogger; }
            set { _options.FormatLogger = value; }
        }

```  
should be
```
        public ImmutableArray<string> CopyrightHeader
        {
            get
            {
                return _options.CopyrightHeader;
            }
            set
            {
                _options.CopyrightHeader = value;
            }
        }

        public ImmutableArray<string[]> PreprocessorConfigurations
        {
            get
            {
                return _options.PreprocessorConfigurations; }
            set
            {
                _options.PreprocessorConfigurations = value;
            }
        }

        public ImmutableArray<string> FileNames
        {
            get
            {
                return _options.FileNames;
            }
            set
            {
                _options.FileNames = value;
            }
        }

        public IFormatLogger FormatLogger
        {
            get
            {
                return _options.FormatLogger;
            }
            set
            {
                _options.FormatLogger = value;
            }
        }
```

Or is it a case of do as I say, rather that do as I do?

**Comment by terrajobst** [comment] 2015-02-09 21:28
No, that's a case of us still making progress on making this tool more integrated in our own workflows.

/cc @jaredpar

**Comment by jaredpar** [comment] 2015-02-09 21:49
@terrajobst i was under the impression that single line properties were allowed.  If that's not the case it's probably a rule we should consider given the huge usage within all of the code bases.  

@AdamSpeight2008 

The tool is indeed on occasion out of date with the standards.  As @terrajobst mentioned we still don't have the tooling level we'd like to make code formatting a silent and automatic part of our daily development.  It's planned but not here yet.

Also there are simply gaps between the what the style guidelines prefer and what the tool enforces.  All such known cases are filed as Issues and labeled with "Guideline Gap".

**Comment by terrajobst** [comment] 2015-02-10 00:52
@jaredpar, so I misread. I was under the impression that it's about the messed up indentation. Yes, [single line accessors are explicitly allowed](https://github.com/dotnet/corefx/wiki/Contributing#example-file) by our example file:

```csharp
public int Count
{
    get { return _count; }
}
```

**Comment by jaredpar** [comment] 2015-02-10 01:02
If that is the case then this appears to be by design. Closing.

**Closed by jaredpar** 2015-02-10 01:02 UTC
